select id, engine_manufacturer_id as manufacturer, name, full_name, capacity, configuration, aspiration
from engine e;

select id,
       name,
       full_name,
       country_id,
       best_championship_position,
       best_starting_grid_position,
       best_race_result,
       total_championship_wins,
       total_race_entries,
       total_race_starts,
       total_race_wins,
       total_1_and_2_finishes,
       total_race_laps,
       total_podiums,
       total_podium_races,
       total_points,
       total_championship_points,
       total_pole_positions,
       total_fastest_laps
from constructor c;


select race_id,
       type,
       position_display_order,
       position_number,
       position_text,
       driver_number,
       driver_id,
       constructor_id,
       engine_manufacturer_id,
       tyre_manufacturer_id,
       practice_time,
       practice_time_millis,
       practice_gap,
       practice_gap_millis,
       practice_interval,
       practice_interval_millis,
       practice_laps,
       qualifying_time,
       qualifying_time_millis,
       qualifying_q1,
       qualifying_q1_millis,
       qualifying_q2,
       qualifying_q2_millis,
       qualifying_q3,
       qualifying_q3_millis,
       qualifying_gap,
       qualifying_gap_millis,
       qualifying_interval,
       qualifying_interval_millis,
       qualifying_laps,
       starting_grid_position_qualification_position_number,
       starting_grid_position_qualification_position_text,
       starting_grid_position_grid_penalty,
       starting_grid_position_grid_penalty_positions,
       starting_grid_position_time,
       starting_grid_position_time_millis,
       race_shared_car,
       race_laps,
       race_time,
       race_time_millis,
       race_time_penalty,
       race_time_penalty_millis,
       race_gap,
       race_gap_millis,
       race_gap_laps,
       race_interval,
       race_interval_millis,
       race_reason_retired,
       race_points,
       race_pole_position,
       race_qualification_position_number,
       race_qualification_position_text,
       race_grid_position_number,
       race_grid_position_text,
       race_positions_gained,
       race_pit_stops,
       race_fastest_lap,
       race_driver_of_the_day,
       race_grand_slam,
       fastest_lap_lap,
       fastest_lap_time,
       fastest_lap_time_millis,
       fastest_lap_gap,
       fastest_lap_gap_millis,
       fastest_lap_interval,
       fastest_lap_interval_millis,
       pit_stop_stop,
       pit_stop_lap,
       pit_stop_time,
       pit_stop_time_millis,
       driver_of_the_day_percentage
from race_data
order by race_id
offset 10 fetch next 20 rows only;
